-- vymaz vsechny zaznamy 
DELETE FROM  enum_country ;
-- nacti vsechny staty
INSERT INTO enum_country (id,country) VALUES ( 'AF' , 'AFGHANISTAN' );
INSERT INTO enum_country (id,country) VALUES ( 'AX' , 'ALAND ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'AL' , 'ALBANIA' );
INSERT INTO enum_country (id,country) VALUES ( 'DZ' , 'ALGERIA' );
INSERT INTO enum_country (id,country) VALUES ( 'AS' , 'AMERICAN SAMOA' );
INSERT INTO enum_country (id,country) VALUES ( 'AD' , 'ANDORRA' );
INSERT INTO enum_country (id,country) VALUES ( 'AO' , 'ANGOLA' );
INSERT INTO enum_country (id,country) VALUES ( 'AI' , 'ANGUILLA' );
INSERT INTO enum_country (id,country) VALUES ( 'AQ' , 'ANTARCTICA' );
INSERT INTO enum_country (id,country) VALUES ( 'AG' , 'ANTIGUA AND BARBUDA' );
INSERT INTO enum_country (id,country) VALUES ( 'AR' , 'ARGENTINA' );
INSERT INTO enum_country (id,country) VALUES ( 'AM' , 'ARMENIA' );
INSERT INTO enum_country (id,country) VALUES ( 'AW' , 'ARUBA' );
INSERT INTO enum_country (id,country) VALUES ( 'AU' , 'AUSTRALIA' );
INSERT INTO enum_country (id,country) VALUES ( 'AT' , 'AUSTRIA' );
INSERT INTO enum_country (id,country) VALUES ( 'AZ' , 'AZERBAIJAN' );
INSERT INTO enum_country (id,country) VALUES ( 'BS' , 'BAHAMAS' );
INSERT INTO enum_country (id,country) VALUES ( 'BH' , 'BAHRAIN' );
INSERT INTO enum_country (id,country) VALUES ( 'BD' , 'BANGLADESH' );
INSERT INTO enum_country (id,country) VALUES ( 'BB' , 'BARBADOS' );
INSERT INTO enum_country (id,country) VALUES ( 'BY' , 'BELARUS' );
INSERT INTO enum_country (id,country) VALUES ( 'BE' , 'BELGIUM' );
INSERT INTO enum_country (id,country) VALUES ( 'BZ' , 'BELIZE' );
INSERT INTO enum_country (id,country) VALUES ( 'BJ' , 'BENIN' );
INSERT INTO enum_country (id,country) VALUES ( 'BM' , 'BERMUDA' );
INSERT INTO enum_country (id,country) VALUES ( 'BT' , 'BHUTAN' );
INSERT INTO enum_country (id,country) VALUES ( 'BO' , 'BOLIVIA' );
INSERT INTO enum_country (id,country) VALUES ( 'BA' , 'BOSNIA AND HERZEGOVINA' );
INSERT INTO enum_country (id,country) VALUES ( 'BW' , 'BOTSWANA' );
INSERT INTO enum_country (id,country) VALUES ( 'BV' , 'BOUVET ISLAND' );
INSERT INTO enum_country (id,country) VALUES ( 'BR' , 'BRAZIL' );
INSERT INTO enum_country (id,country) VALUES ( 'IO' , 'BRITISH INDIAN OCEAN TERRITORY' );
INSERT INTO enum_country (id,country) VALUES ( 'BN' , 'BRUNEI DARUSSALAM' );
INSERT INTO enum_country (id,country) VALUES ( 'BG' , 'BULGARIA' );
INSERT INTO enum_country (id,country) VALUES ( 'BF' , 'BURKINA FASO' );
INSERT INTO enum_country (id,country) VALUES ( 'BI' , 'BURUNDI' );
INSERT INTO enum_country (id,country) VALUES ( 'KH' , 'CAMBODIA' );
INSERT INTO enum_country (id,country) VALUES ( 'CM' , 'CAMEROON' );
INSERT INTO enum_country (id,country) VALUES ( 'CA' , 'CANADA' );
INSERT INTO enum_country (id,country) VALUES ( 'CV' , 'CAPE VERDE' );
INSERT INTO enum_country (id,country) VALUES ( 'KY' , 'CAYMAN ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'CF' , 'CENTRAL AFRICAN REPUBLIC' );
INSERT INTO enum_country (id,country) VALUES ( 'TD' , 'CHAD' );
INSERT INTO enum_country (id,country) VALUES ( 'CL' , 'CHILE' );
INSERT INTO enum_country (id,country) VALUES ( 'CN' , 'CHINA' );
INSERT INTO enum_country (id,country) VALUES ( 'CX' , 'CHRISTMAS ISLAND' );
INSERT INTO enum_country (id,country) VALUES ( 'CC' , 'COCOS (KEELING); ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'CO' , 'COLOMBIA' );
INSERT INTO enum_country (id,country) VALUES ( 'KM' , 'COMOROS' );
INSERT INTO enum_country (id,country) VALUES ( 'CG' , 'CONGO' );
INSERT INTO enum_country (id,country) VALUES ( 'CD' , 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' );
INSERT INTO enum_country (id,country) VALUES ( 'CK' , 'COOK ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'CR' , 'COSTA RICA' );
INSERT INTO enum_country (id,country) VALUES ( 'CI' , 'COTE D''IVOIRE' );
INSERT INTO enum_country (id,country) VALUES ( 'HR' , 'CROATIA' );
INSERT INTO enum_country (id,country) VALUES ( 'CU' , 'CUBA' );
INSERT INTO enum_country (id,country) VALUES ( 'CY' , 'CYPRUS' );
INSERT INTO enum_country (id,country) VALUES ( 'CZ' , 'CZECH REPUBLIC' );
INSERT INTO enum_country (id,country) VALUES ( 'DK' , 'DENMARK' );
INSERT INTO enum_country (id,country) VALUES ( 'DJ' , 'DJIBOUTI' );
INSERT INTO enum_country (id,country) VALUES ( 'DM' , 'DOMINICA' );
INSERT INTO enum_country (id,country) VALUES ( 'DO' , 'DOMINICAN REPUBLIC' );
INSERT INTO enum_country (id,country) VALUES ( 'EC' , 'ECUADOR' );
INSERT INTO enum_country (id,country) VALUES ( 'EG' , 'EGYPT' );
INSERT INTO enum_country (id,country) VALUES ( 'SV' , 'EL SALVADOR' );
INSERT INTO enum_country (id,country) VALUES ( 'GQ' , 'EQUATORIAL GUINEA' );
INSERT INTO enum_country (id,country) VALUES ( 'ER' , 'ERITREA' );
INSERT INTO enum_country (id,country) VALUES ( 'EE' , 'ESTONIA' );
INSERT INTO enum_country (id,country) VALUES ( 'ET' , 'ETHIOPIA' );
INSERT INTO enum_country (id,country) VALUES ( 'FK' , 'FALKLAND ISLANDS (MALVINAS);' );
INSERT INTO enum_country (id,country) VALUES ( 'FO' , 'FAROE ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'FJ' , 'FIJI' );
INSERT INTO enum_country (id,country) VALUES ( 'FI' , 'FINLAND' );
INSERT INTO enum_country (id,country) VALUES ( 'FR' , 'FRANCE' );
INSERT INTO enum_country (id,country) VALUES ( 'GF' , 'FRENCH GUIANA' );
INSERT INTO enum_country (id,country) VALUES ( 'PF' , 'FRENCH POLYNESIA' );
INSERT INTO enum_country (id,country) VALUES ( 'TF' , 'FRENCH SOUTHERN TERRITORIES' );
INSERT INTO enum_country (id,country) VALUES ( 'GA' , 'GABON' );
INSERT INTO enum_country (id,country) VALUES ( 'GM' , 'GAMBIA' );
INSERT INTO enum_country (id,country) VALUES ( 'GE' , 'GEORGIA' );
INSERT INTO enum_country (id,country) VALUES ( 'DE' , 'GERMANY' );
INSERT INTO enum_country (id,country) VALUES ( 'GH' , 'GHANA' );
INSERT INTO enum_country (id,country) VALUES ( 'GI' , 'GIBRALTAR' );
INSERT INTO enum_country (id,country) VALUES ( 'GR' , 'GREECE' );
INSERT INTO enum_country (id,country) VALUES ( 'GL' , 'GREENLAND' );
INSERT INTO enum_country (id,country) VALUES ( 'GD' , 'GRENADA' );
INSERT INTO enum_country (id,country) VALUES ( 'GP' , 'GUADELOUPE' );
INSERT INTO enum_country (id,country) VALUES ( 'GU' , 'GUAM' );
INSERT INTO enum_country (id,country) VALUES ( 'GT' , 'GUATEMALA' );
INSERT INTO enum_country (id,country) VALUES ( 'GN' , 'GUINEA' );
INSERT INTO enum_country (id,country) VALUES ( 'GW' , 'GUINEA-BISSAU' );
INSERT INTO enum_country (id,country) VALUES ( 'GY' , 'GUYANA' );
INSERT INTO enum_country (id,country) VALUES ( 'HT' , 'HAITI' );
INSERT INTO enum_country (id,country) VALUES ( 'HM' , 'HEARD ISLAND AND MCDONALD ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'VA' , 'HOLY SEE (VATICAN CITY STATE);' );
INSERT INTO enum_country (id,country) VALUES ( 'HN' , 'HONDURAS' );
INSERT INTO enum_country (id,country) VALUES ( 'HK' , 'HONG KONG' );
INSERT INTO enum_country (id,country) VALUES ( 'HU' , 'HUNGARY' );
INSERT INTO enum_country (id,country) VALUES ( 'IS' , 'ICELAND' );
INSERT INTO enum_country (id,country) VALUES ( 'IN' , 'INDIA' );
INSERT INTO enum_country (id,country) VALUES ( 'ID' , 'INDONESIA' );
INSERT INTO enum_country (id,country) VALUES ( 'IR' , 'IRAN, ISLAMIC REPUBLIC OF' );
INSERT INTO enum_country (id,country) VALUES ( 'IQ' , 'IRAQ' );
INSERT INTO enum_country (id,country) VALUES ( 'IE' , 'IRELAND' );
INSERT INTO enum_country (id,country) VALUES ( 'IL' , 'ISRAEL' );
INSERT INTO enum_country (id,country) VALUES ( 'IT' , 'ITALY' );
INSERT INTO enum_country (id,country) VALUES ( 'JM' , 'JAMAICA' );
INSERT INTO enum_country (id,country) VALUES ( 'JP' , 'JAPAN' );
INSERT INTO enum_country (id,country) VALUES ( 'JO' , 'JORDAN' );
INSERT INTO enum_country (id,country) VALUES ( 'KZ' , 'KAZAKHSTAN' );
INSERT INTO enum_country (id,country) VALUES ( 'KE' , 'KENYA' );
INSERT INTO enum_country (id,country) VALUES ( 'KI' , 'KIRIBATI' );
INSERT INTO enum_country (id,country) VALUES ( 'KP' , 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF' );
INSERT INTO enum_country (id,country) VALUES ( 'KR' , 'KOREA, REPUBLIC OF' );
INSERT INTO enum_country (id,country) VALUES ( 'KW' , 'KUWAIT' );
INSERT INTO enum_country (id,country) VALUES ( 'KG' , 'KYRGYZSTAN' );
INSERT INTO enum_country (id,country) VALUES ( 'LA' , 'LAO PEOPLE''S DEMOCRATIC REPUBLIC' );
INSERT INTO enum_country (id,country) VALUES ( 'LV' , 'LATVIA' );
INSERT INTO enum_country (id,country) VALUES ( 'LB' , 'LEBANON' );
INSERT INTO enum_country (id,country) VALUES ( 'LS' , 'LESOTHO' );
INSERT INTO enum_country (id,country) VALUES ( 'LR' , 'LIBERIA' );
INSERT INTO enum_country (id,country) VALUES ( 'LY' , 'LIBYAN ARAB JAMAHIRIYA' );
INSERT INTO enum_country (id,country) VALUES ( 'LI' , 'LIECHTENSTEIN' );
INSERT INTO enum_country (id,country) VALUES ( 'LT' , 'LITHUANIA' );
INSERT INTO enum_country (id,country) VALUES ( 'LU' , 'LUXEMBOURG' );
INSERT INTO enum_country (id,country) VALUES ( 'MO' , 'MACAO' );
INSERT INTO enum_country (id,country) VALUES ( 'MK' , 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' );
INSERT INTO enum_country (id,country) VALUES ( 'MG' , 'MADAGASCAR' );
INSERT INTO enum_country (id,country) VALUES ( 'MW' , 'MALAWI' );
INSERT INTO enum_country (id,country) VALUES ( 'MY' , 'MALAYSIA' );
INSERT INTO enum_country (id,country) VALUES ( 'MV' , 'MALDIVES' );
INSERT INTO enum_country (id,country) VALUES ( 'ML' , 'MALI' );
INSERT INTO enum_country (id,country) VALUES ( 'MT' , 'MALTA' );
INSERT INTO enum_country (id,country) VALUES ( 'MH' , 'MARSHALL ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'MQ' , 'MARTINIQUE' );
INSERT INTO enum_country (id,country) VALUES ( 'MR' , 'MAURITANIA' );
INSERT INTO enum_country (id,country) VALUES ( 'MU' , 'MAURITIUS' );
INSERT INTO enum_country (id,country) VALUES ( 'YT' , 'MAYOTTE' );
INSERT INTO enum_country (id,country) VALUES ( 'MX' , 'MEXICO' );
INSERT INTO enum_country (id,country) VALUES ( 'FM' , 'MICRONESIA, FEDERATED STATES OF' );
INSERT INTO enum_country (id,country) VALUES ( 'MD' , 'MOLDOVA, REPUBLIC OF' );
INSERT INTO enum_country (id,country) VALUES ( 'MC' , 'MONACO' );
INSERT INTO enum_country (id,country) VALUES ( 'MN' , 'MONGOLIA' );
INSERT INTO enum_country (id,country) VALUES ( 'MS' , 'MONTSERRAT' );
INSERT INTO enum_country (id,country) VALUES ( 'MA' , 'MOROCCO' );
INSERT INTO enum_country (id,country) VALUES ( 'MZ' , 'MOZAMBIQUE' );
INSERT INTO enum_country (id,country) VALUES ( 'MM' , 'MYANMAR' );
INSERT INTO enum_country (id,country) VALUES ( 'NA' , 'NAMIBIA' );
INSERT INTO enum_country (id,country) VALUES ( 'NR' , 'NAURU' );
INSERT INTO enum_country (id,country) VALUES ( 'NP' , 'NEPAL' );
INSERT INTO enum_country (id,country) VALUES ( 'NL' , 'NETHERLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'AN' , 'NETHERLANDS ANTILLES' );
INSERT INTO enum_country (id,country) VALUES ( 'NC' , 'NEW CALEDONIA' );
INSERT INTO enum_country (id,country) VALUES ( 'NZ' , 'NEW ZEALAND' );
INSERT INTO enum_country (id,country) VALUES ( 'NI' , 'NICARAGUA' );
INSERT INTO enum_country (id,country) VALUES ( 'NE' , 'NIGER' );
INSERT INTO enum_country (id,country) VALUES ( 'NG' , 'NIGERIA' );
INSERT INTO enum_country (id,country) VALUES ( 'NU' , 'NIUE' );
INSERT INTO enum_country (id,country) VALUES ( 'NF' , 'NORFOLK ISLAND' );
INSERT INTO enum_country (id,country) VALUES ( 'MP' , 'NORTHERN MARIANA ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'NO' , 'NORWAY' );
INSERT INTO enum_country (id,country) VALUES ( 'OM' , 'OMAN' );
INSERT INTO enum_country (id,country) VALUES ( 'PK' , 'PAKISTAN' );
INSERT INTO enum_country (id,country) VALUES ( 'PW' , 'PALAU' );
INSERT INTO enum_country (id,country) VALUES ( 'PS' , 'PALESTINIAN TERRITORY, OCCUPIED' );
INSERT INTO enum_country (id,country) VALUES ( 'PA' , 'PANAMA' );
INSERT INTO enum_country (id,country) VALUES ( 'PG' , 'PAPUA NEW GUINEA' );
INSERT INTO enum_country (id,country) VALUES ( 'PY' , 'PARAGUAY' );
INSERT INTO enum_country (id,country) VALUES ( 'PE' , 'PERU' );
INSERT INTO enum_country (id,country) VALUES ( 'PH' , 'PHILIPPINES' );
INSERT INTO enum_country (id,country) VALUES ( 'PN' , 'PITCAIRN' );
INSERT INTO enum_country (id,country) VALUES ( 'PL' , 'POLAND' );
INSERT INTO enum_country (id,country) VALUES ( 'PT' , 'PORTUGAL' );
INSERT INTO enum_country (id,country) VALUES ( 'PR' , 'PUERTO RICO' );
INSERT INTO enum_country (id,country) VALUES ( 'QA' , 'QATAR' );
INSERT INTO enum_country (id,country) VALUES ( 'RE' , 'REUNION' );
INSERT INTO enum_country (id,country) VALUES ( 'RO' , 'ROMANIA' );
INSERT INTO enum_country (id,country) VALUES ( 'RU' , 'RUSSIAN FEDERATION' );
INSERT INTO enum_country (id,country) VALUES ( 'RW' , 'RWANDA' );
INSERT INTO enum_country (id,country) VALUES ( 'SH' , 'SAINT HELENA' );
INSERT INTO enum_country (id,country) VALUES ( 'KN' , 'SAINT KITTS AND NEVIS' );
INSERT INTO enum_country (id,country) VALUES ( 'LC' , 'SAINT LUCIA' );
INSERT INTO enum_country (id,country) VALUES ( 'PM' , 'SAINT PIERRE AND MIQUELON' );
INSERT INTO enum_country (id,country) VALUES ( 'VC' , 'SAINT VINCENT AND THE GRENADINES' );
INSERT INTO enum_country (id,country) VALUES ( 'WS' , 'SAMOA' );
INSERT INTO enum_country (id,country) VALUES ( 'SM' , 'SAN MARINO' );
INSERT INTO enum_country (id,country) VALUES ( 'ST' , 'SAO TOME AND PRINCIPE' );
INSERT INTO enum_country (id,country) VALUES ( 'SA' , 'SAUDI ARABIA' );
INSERT INTO enum_country (id,country) VALUES ( 'SN' , 'SENEGAL' );
INSERT INTO enum_country (id,country) VALUES ( 'CS' , 'SERBIA AND MONTENEGRO' );
INSERT INTO enum_country (id,country) VALUES ( 'SC' , 'SEYCHELLES' );
INSERT INTO enum_country (id,country) VALUES ( 'SL' , 'SIERRA LEONE' );
INSERT INTO enum_country (id,country) VALUES ( 'SG' , 'SINGAPORE' );
INSERT INTO enum_country (id,country) VALUES ( 'SK' , 'SLOVAKIA' );
INSERT INTO enum_country (id,country) VALUES ( 'SI' , 'SLOVENIA' );
INSERT INTO enum_country (id,country) VALUES ( 'SB' , 'SOLOMON ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'SO' , 'SOMALIA' );
INSERT INTO enum_country (id,country) VALUES ( 'ZA' , 'SOUTH AFRICA' );
INSERT INTO enum_country (id,country) VALUES ( 'GS' , 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'ES' , 'SPAIN' );
INSERT INTO enum_country (id,country) VALUES ( 'LK' , 'SRI LANKA' );
INSERT INTO enum_country (id,country) VALUES ( 'SD' , 'SUDAN' );
INSERT INTO enum_country (id,country) VALUES ( 'SR' , 'SURINAME' );
INSERT INTO enum_country (id,country) VALUES ( 'SJ' , 'SVALBARD AND JAN MAYEN' );
INSERT INTO enum_country (id,country) VALUES ( 'SZ' , 'SWAZILAND' );
INSERT INTO enum_country (id,country) VALUES ( 'SE' , 'SWEDEN' );
INSERT INTO enum_country (id,country) VALUES ( 'CH' , 'SWITZERLAND' );
INSERT INTO enum_country (id,country) VALUES ( 'SY' , 'SYRIAN ARAB REPUBLIC' );
INSERT INTO enum_country (id,country) VALUES ( 'TW' , 'TAIWAN, PROVINCE OF CHINA' );
INSERT INTO enum_country (id,country) VALUES ( 'TJ' , 'TAJIKISTAN' );
INSERT INTO enum_country (id,country) VALUES ( 'TZ' , 'TANZANIA, UNITED REPUBLIC OF' );
INSERT INTO enum_country (id,country) VALUES ( 'TH' , 'THAILAND' );
INSERT INTO enum_country (id,country) VALUES ( 'TL' , 'TIMOR-LESTE' );
INSERT INTO enum_country (id,country) VALUES ( 'TG' , 'TOGO' );
INSERT INTO enum_country (id,country) VALUES ( 'TK' , 'TOKELAU' );
INSERT INTO enum_country (id,country) VALUES ( 'TO' , 'TONGA' );
INSERT INTO enum_country (id,country) VALUES ( 'TT' , 'TRINIDAD AND TOBAGO' );
INSERT INTO enum_country (id,country) VALUES ( 'TN' , 'TUNISIA' );
INSERT INTO enum_country (id,country) VALUES ( 'TR' , 'TURKEY' );
INSERT INTO enum_country (id,country) VALUES ( 'TM' , 'TURKMENISTAN' );
INSERT INTO enum_country (id,country) VALUES ( 'TC' , 'TURKS AND CAICOS ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'TV' , 'TUVALU' );
INSERT INTO enum_country (id,country) VALUES ( 'UG' , 'UGANDA' );
INSERT INTO enum_country (id,country) VALUES ( 'UA' , 'UKRAINE' );
INSERT INTO enum_country (id,country) VALUES ( 'AE' , 'UNITED ARAB EMIRATES' );
INSERT INTO enum_country (id,country) VALUES ( 'GB' , 'UNITED KINGDOM' );
INSERT INTO enum_country (id,country) VALUES ( 'US' , 'UNITED STATES' );
INSERT INTO enum_country (id,country) VALUES ( 'UM' , 'UNITED STATES MINOR OUTLYING ISLANDS' );
INSERT INTO enum_country (id,country) VALUES ( 'UY' , 'URUGUAY' );
INSERT INTO enum_country (id,country) VALUES ( 'UZ' , 'UZBEKISTAN' );
INSERT INTO enum_country (id,country) VALUES ( 'VU' , 'VANUATU' );
INSERT INTO enum_country (id,country) VALUES ( 'VE' , 'VENEZUELA' );
INSERT INTO enum_country (id,country) VALUES ( 'VN' , 'VIET NAM' );
INSERT INTO enum_country (id,country) VALUES ( 'VG' , 'VIRGIN ISLANDS, BRITISH' );
INSERT INTO enum_country (id,country) VALUES ( 'VI' , 'VIRGIN ISLANDS, U.S.' );
INSERT INTO enum_country (id,country) VALUES ( 'WF' , 'WALLIS AND FUTUNA' );
INSERT INTO enum_country (id,country) VALUES ( 'EH' , 'WESTERN SAHARA' );
INSERT INTO enum_country (id,country) VALUES ( 'YE' , 'YEMEN' );
INSERT INTO enum_country (id,country) VALUES ( 'ZM' , 'ZAMBIA' );
INSERT INTO enum_country (id,country) VALUES ( 'ZW' , 'ZIMBABWE' );
