-- vymaz vsechny zaznamy 
DELETE FROM  enum_country ;
-- nacti vsechny staty
INSERT INTO enum_country VALUES( 'AF' , 'AFGHANISTAN' );
INSERT INTO enum_country VALUES( 'AX' , 'ALAND ISLANDS' );
INSERT INTO enum_country VALUES( 'AL' , 'ALBANIA' );
INSERT INTO enum_country VALUES( 'DZ' , 'ALGERIA' );
INSERT INTO enum_country VALUES( 'AS' , 'AMERICAN SAMOA' );
INSERT INTO enum_country VALUES( 'AD' , 'ANDORRA' );
INSERT INTO enum_country VALUES( 'AO' , 'ANGOLA' );
INSERT INTO enum_country VALUES( 'AI' , 'ANGUILLA' );
INSERT INTO enum_country VALUES( 'AQ' , 'ANTARCTICA' );
INSERT INTO enum_country VALUES( 'AG' , 'ANTIGUA AND BARBUDA' );
INSERT INTO enum_country VALUES( 'AR' , 'ARGENTINA' );
INSERT INTO enum_country VALUES( 'AM' , 'ARMENIA' );
INSERT INTO enum_country VALUES( 'AW' , 'ARUBA' );
INSERT INTO enum_country VALUES( 'AU' , 'AUSTRALIA' );
INSERT INTO enum_country VALUES( 'AT' , 'AUSTRIA' );
INSERT INTO enum_country VALUES( 'AZ' , 'AZERBAIJAN' );
INSERT INTO enum_country VALUES( 'BS' , 'BAHAMAS' );
INSERT INTO enum_country VALUES( 'BH' , 'BAHRAIN' );
INSERT INTO enum_country VALUES( 'BD' , 'BANGLADESH' );
INSERT INTO enum_country VALUES( 'BB' , 'BARBADOS' );
INSERT INTO enum_country VALUES( 'BY' , 'BELARUS' );
INSERT INTO enum_country VALUES( 'BE' , 'BELGIUM' );
INSERT INTO enum_country VALUES( 'BZ' , 'BELIZE' );
INSERT INTO enum_country VALUES( 'BJ' , 'BENIN' );
INSERT INTO enum_country VALUES( 'BM' , 'BERMUDA' );
INSERT INTO enum_country VALUES( 'BT' , 'BHUTAN' );
INSERT INTO enum_country VALUES( 'BO' , 'BOLIVIA' );
INSERT INTO enum_country VALUES( 'BA' , 'BOSNIA AND HERZEGOVINA' );
INSERT INTO enum_country VALUES( 'BW' , 'BOTSWANA' );
INSERT INTO enum_country VALUES( 'BV' , 'BOUVET ISLAND' );
INSERT INTO enum_country VALUES( 'BR' , 'BRAZIL' );
INSERT INTO enum_country VALUES( 'IO' , 'BRITISH INDIAN OCEAN TERRITORY' );
INSERT INTO enum_country VALUES( 'BN' , 'BRUNEI DARUSSALAM' );
INSERT INTO enum_country VALUES( 'BG' , 'BULGARIA' );
INSERT INTO enum_country VALUES( 'BF' , 'BURKINA FASO' );
INSERT INTO enum_country VALUES( 'BI' , 'BURUNDI' );
INSERT INTO enum_country VALUES( 'KH' , 'CAMBODIA' );
INSERT INTO enum_country VALUES( 'CM' , 'CAMEROON' );
INSERT INTO enum_country VALUES( 'CA' , 'CANADA' );
INSERT INTO enum_country VALUES( 'CV' , 'CAPE VERDE' );
INSERT INTO enum_country VALUES( 'KY' , 'CAYMAN ISLANDS' );
INSERT INTO enum_country VALUES( 'CF' , 'CENTRAL AFRICAN REPUBLIC' );
INSERT INTO enum_country VALUES( 'TD' , 'CHAD' );
INSERT INTO enum_country VALUES( 'CL' , 'CHILE' );
INSERT INTO enum_country VALUES( 'CN' , 'CHINA' );
INSERT INTO enum_country VALUES( 'CX' , 'CHRISTMAS ISLAND' );
INSERT INTO enum_country VALUES( 'CC' , 'COCOS (KEELING); ISLANDS' );
INSERT INTO enum_country VALUES( 'CO' , 'COLOMBIA' );
INSERT INTO enum_country VALUES( 'KM' , 'COMOROS' );
INSERT INTO enum_country VALUES( 'CG' , 'CONGO' );
INSERT INTO enum_country VALUES( 'CD' , 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' );
INSERT INTO enum_country VALUES( 'CK' , 'COOK ISLANDS' );
INSERT INTO enum_country VALUES( 'CR' , 'COSTA RICA' );
INSERT INTO enum_country VALUES( 'CI' , 'COTE D''IVOIRE' );
INSERT INTO enum_country VALUES( 'HR' , 'CROATIA' );
INSERT INTO enum_country VALUES( 'CU' , 'CUBA' );
INSERT INTO enum_country VALUES( 'CY' , 'CYPRUS' );
INSERT INTO enum_country VALUES( 'CZ' , 'CZECH REPUBLIC' );
INSERT INTO enum_country VALUES( 'DK' , 'DENMARK' );
INSERT INTO enum_country VALUES( 'DJ' , 'DJIBOUTI' );
INSERT INTO enum_country VALUES( 'DM' , 'DOMINICA' );
INSERT INTO enum_country VALUES( 'DO' , 'DOMINICAN REPUBLIC' );
INSERT INTO enum_country VALUES( 'EC' , 'ECUADOR' );
INSERT INTO enum_country VALUES( 'EG' , 'EGYPT' );
INSERT INTO enum_country VALUES( 'SV' , 'EL SALVADOR' );
INSERT INTO enum_country VALUES( 'GQ' , 'EQUATORIAL GUINEA' );
INSERT INTO enum_country VALUES( 'ER' , 'ERITREA' );
INSERT INTO enum_country VALUES( 'EE' , 'ESTONIA' );
INSERT INTO enum_country VALUES( 'ET' , 'ETHIOPIA' );
INSERT INTO enum_country VALUES( 'FK' , 'FALKLAND ISLANDS (MALVINAS);' );
INSERT INTO enum_country VALUES( 'FO' , 'FAROE ISLANDS' );
INSERT INTO enum_country VALUES( 'FJ' , 'FIJI' );
INSERT INTO enum_country VALUES( 'FI' , 'FINLAND' );
INSERT INTO enum_country VALUES( 'FR' , 'FRANCE' );
INSERT INTO enum_country VALUES( 'GF' , 'FRENCH GUIANA' );
INSERT INTO enum_country VALUES( 'PF' , 'FRENCH POLYNESIA' );
INSERT INTO enum_country VALUES( 'TF' , 'FRENCH SOUTHERN TERRITORIES' );
INSERT INTO enum_country VALUES( 'GA' , 'GABON' );
INSERT INTO enum_country VALUES( 'GM' , 'GAMBIA' );
INSERT INTO enum_country VALUES( 'GE' , 'GEORGIA' );
INSERT INTO enum_country VALUES( 'DE' , 'GERMANY' );
INSERT INTO enum_country VALUES( 'GH' , 'GHANA' );
INSERT INTO enum_country VALUES( 'GI' , 'GIBRALTAR' );
INSERT INTO enum_country VALUES( 'GR' , 'GREECE' );
INSERT INTO enum_country VALUES( 'GL' , 'GREENLAND' );
INSERT INTO enum_country VALUES( 'GD' , 'GRENADA' );
INSERT INTO enum_country VALUES( 'GP' , 'GUADELOUPE' );
INSERT INTO enum_country VALUES( 'GU' , 'GUAM' );
INSERT INTO enum_country VALUES( 'GT' , 'GUATEMALA' );
INSERT INTO enum_country VALUES( 'GN' , 'GUINEA' );
INSERT INTO enum_country VALUES( 'GW' , 'GUINEA-BISSAU' );
INSERT INTO enum_country VALUES( 'GY' , 'GUYANA' );
INSERT INTO enum_country VALUES( 'HT' , 'HAITI' );
INSERT INTO enum_country VALUES( 'HM' , 'HEARD ISLAND AND MCDONALD ISLANDS' );
INSERT INTO enum_country VALUES( 'VA' , 'HOLY SEE (VATICAN CITY STATE);' );
INSERT INTO enum_country VALUES( 'HN' , 'HONDURAS' );
INSERT INTO enum_country VALUES( 'HK' , 'HONG KONG' );
INSERT INTO enum_country VALUES( 'HU' , 'HUNGARY' );
INSERT INTO enum_country VALUES( 'IS' , 'ICELAND' );
INSERT INTO enum_country VALUES( 'IN' , 'INDIA' );
INSERT INTO enum_country VALUES( 'ID' , 'INDONESIA' );
INSERT INTO enum_country VALUES( 'IR' , 'IRAN, ISLAMIC REPUBLIC OF' );
INSERT INTO enum_country VALUES( 'IQ' , 'IRAQ' );
INSERT INTO enum_country VALUES( 'IE' , 'IRELAND' );
INSERT INTO enum_country VALUES( 'IL' , 'ISRAEL' );
INSERT INTO enum_country VALUES( 'IT' , 'ITALY' );
INSERT INTO enum_country VALUES( 'JM' , 'JAMAICA' );
INSERT INTO enum_country VALUES( 'JP' , 'JAPAN' );
INSERT INTO enum_country VALUES( 'JO' , 'JORDAN' );
INSERT INTO enum_country VALUES( 'KZ' , 'KAZAKHSTAN' );
INSERT INTO enum_country VALUES( 'KE' , 'KENYA' );
INSERT INTO enum_country VALUES( 'KI' , 'KIRIBATI' );
INSERT INTO enum_country VALUES( 'KP' , 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF' );
INSERT INTO enum_country VALUES( 'KR' , 'KOREA, REPUBLIC OF' );
INSERT INTO enum_country VALUES( 'KW' , 'KUWAIT' );
INSERT INTO enum_country VALUES( 'KG' , 'KYRGYZSTAN' );
INSERT INTO enum_country VALUES( 'LA' , 'LAO PEOPLE''S DEMOCRATIC REPUBLIC' );
INSERT INTO enum_country VALUES( 'LV' , 'LATVIA' );
INSERT INTO enum_country VALUES( 'LB' , 'LEBANON' );
INSERT INTO enum_country VALUES( 'LS' , 'LESOTHO' );
INSERT INTO enum_country VALUES( 'LR' , 'LIBERIA' );
INSERT INTO enum_country VALUES( 'LY' , 'LIBYAN ARAB JAMAHIRIYA' );
INSERT INTO enum_country VALUES( 'LI' , 'LIECHTENSTEIN' );
INSERT INTO enum_country VALUES( 'LT' , 'LITHUANIA' );
INSERT INTO enum_country VALUES( 'LU' , 'LUXEMBOURG' );
INSERT INTO enum_country VALUES( 'MO' , 'MACAO' );
INSERT INTO enum_country VALUES( 'MK' , 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' );
INSERT INTO enum_country VALUES( 'MG' , 'MADAGASCAR' );
INSERT INTO enum_country VALUES( 'MW' , 'MALAWI' );
INSERT INTO enum_country VALUES( 'MY' , 'MALAYSIA' );
INSERT INTO enum_country VALUES( 'MV' , 'MALDIVES' );
INSERT INTO enum_country VALUES( 'ML' , 'MALI' );
INSERT INTO enum_country VALUES( 'MT' , 'MALTA' );
INSERT INTO enum_country VALUES( 'MH' , 'MARSHALL ISLANDS' );
INSERT INTO enum_country VALUES( 'MQ' , 'MARTINIQUE' );
INSERT INTO enum_country VALUES( 'MR' , 'MAURITANIA' );
INSERT INTO enum_country VALUES( 'MU' , 'MAURITIUS' );
INSERT INTO enum_country VALUES( 'YT' , 'MAYOTTE' );
INSERT INTO enum_country VALUES( 'MX' , 'MEXICO' );
INSERT INTO enum_country VALUES( 'FM' , 'MICRONESIA, FEDERATED STATES OF' );
INSERT INTO enum_country VALUES( 'MD' , 'MOLDOVA, REPUBLIC OF' );
INSERT INTO enum_country VALUES( 'MC' , 'MONACO' );
INSERT INTO enum_country VALUES( 'MN' , 'MONGOLIA' );
INSERT INTO enum_country VALUES( 'MS' , 'MONTSERRAT' );
INSERT INTO enum_country VALUES( 'MA' , 'MOROCCO' );
INSERT INTO enum_country VALUES( 'MZ' , 'MOZAMBIQUE' );
INSERT INTO enum_country VALUES( 'MM' , 'MYANMAR' );
INSERT INTO enum_country VALUES( 'NA' , 'NAMIBIA' );
INSERT INTO enum_country VALUES( 'NR' , 'NAURU' );
INSERT INTO enum_country VALUES( 'NP' , 'NEPAL' );
INSERT INTO enum_country VALUES( 'NL' , 'NETHERLANDS' );
INSERT INTO enum_country VALUES( 'AN' , 'NETHERLANDS ANTILLES' );
INSERT INTO enum_country VALUES( 'NC' , 'NEW CALEDONIA' );
INSERT INTO enum_country VALUES( 'NZ' , 'NEW ZEALAND' );
INSERT INTO enum_country VALUES( 'NI' , 'NICARAGUA' );
INSERT INTO enum_country VALUES( 'NE' , 'NIGER' );
INSERT INTO enum_country VALUES( 'NG' , 'NIGERIA' );
INSERT INTO enum_country VALUES( 'NU' , 'NIUE' );
INSERT INTO enum_country VALUES( 'NF' , 'NORFOLK ISLAND' );
INSERT INTO enum_country VALUES( 'MP' , 'NORTHERN MARIANA ISLANDS' );
INSERT INTO enum_country VALUES( 'NO' , 'NORWAY' );
INSERT INTO enum_country VALUES( 'OM' , 'OMAN' );
INSERT INTO enum_country VALUES( 'PK' , 'PAKISTAN' );
INSERT INTO enum_country VALUES( 'PW' , 'PALAU' );
INSERT INTO enum_country VALUES( 'PS' , 'PALESTINIAN TERRITORY, OCCUPIED' );
INSERT INTO enum_country VALUES( 'PA' , 'PANAMA' );
INSERT INTO enum_country VALUES( 'PG' , 'PAPUA NEW GUINEA' );
INSERT INTO enum_country VALUES( 'PY' , 'PARAGUAY' );
INSERT INTO enum_country VALUES( 'PE' , 'PERU' );
INSERT INTO enum_country VALUES( 'PH' , 'PHILIPPINES' );
INSERT INTO enum_country VALUES( 'PN' , 'PITCAIRN' );
INSERT INTO enum_country VALUES( 'PL' , 'POLAND' );
INSERT INTO enum_country VALUES( 'PT' , 'PORTUGAL' );
INSERT INTO enum_country VALUES( 'PR' , 'PUERTO RICO' );
INSERT INTO enum_country VALUES( 'QA' , 'QATAR' );
INSERT INTO enum_country VALUES( 'RE' , 'REUNION' );
INSERT INTO enum_country VALUES( 'RO' , 'ROMANIA' );
INSERT INTO enum_country VALUES( 'RU' , 'RUSSIAN FEDERATION' );
INSERT INTO enum_country VALUES( 'RW' , 'RWANDA' );
INSERT INTO enum_country VALUES( 'SH' , 'SAINT HELENA' );
INSERT INTO enum_country VALUES( 'KN' , 'SAINT KITTS AND NEVIS' );
INSERT INTO enum_country VALUES( 'LC' , 'SAINT LUCIA' );
INSERT INTO enum_country VALUES( 'PM' , 'SAINT PIERRE AND MIQUELON' );
INSERT INTO enum_country VALUES( 'VC' , 'SAINT VINCENT AND THE GRENADINES' );
INSERT INTO enum_country VALUES( 'WS' , 'SAMOA' );
INSERT INTO enum_country VALUES( 'SM' , 'SAN MARINO' );
INSERT INTO enum_country VALUES( 'ST' , 'SAO TOME AND PRINCIPE' );
INSERT INTO enum_country VALUES( 'SA' , 'SAUDI ARABIA' );
INSERT INTO enum_country VALUES( 'SN' , 'SENEGAL' );
INSERT INTO enum_country VALUES( 'CS' , 'SERBIA AND MONTENEGRO' );
INSERT INTO enum_country VALUES( 'SC' , 'SEYCHELLES' );
INSERT INTO enum_country VALUES( 'SL' , 'SIERRA LEONE' );
INSERT INTO enum_country VALUES( 'SG' , 'SINGAPORE' );
INSERT INTO enum_country VALUES( 'SK' , 'SLOVAKIA' );
INSERT INTO enum_country VALUES( 'SI' , 'SLOVENIA' );
INSERT INTO enum_country VALUES( 'SB' , 'SOLOMON ISLANDS' );
INSERT INTO enum_country VALUES( 'SO' , 'SOMALIA' );
INSERT INTO enum_country VALUES( 'ZA' , 'SOUTH AFRICA' );
INSERT INTO enum_country VALUES( 'GS' , 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' );
INSERT INTO enum_country VALUES( 'ES' , 'SPAIN' );
INSERT INTO enum_country VALUES( 'LK' , 'SRI LANKA' );
INSERT INTO enum_country VALUES( 'SD' , 'SUDAN' );
INSERT INTO enum_country VALUES( 'SR' , 'SURINAME' );
INSERT INTO enum_country VALUES( 'SJ' , 'SVALBARD AND JAN MAYEN' );
INSERT INTO enum_country VALUES( 'SZ' , 'SWAZILAND' );
INSERT INTO enum_country VALUES( 'SE' , 'SWEDEN' );
INSERT INTO enum_country VALUES( 'CH' , 'SWITZERLAND' );
INSERT INTO enum_country VALUES( 'SY' , 'SYRIAN ARAB REPUBLIC' );
INSERT INTO enum_country VALUES( 'TW' , 'TAIWAN, PROVINCE OF CHINA' );
INSERT INTO enum_country VALUES( 'TJ' , 'TAJIKISTAN' );
INSERT INTO enum_country VALUES( 'TZ' , 'TANZANIA, UNITED REPUBLIC OF' );
INSERT INTO enum_country VALUES( 'TH' , 'THAILAND' );
INSERT INTO enum_country VALUES( 'TL' , 'TIMOR-LESTE' );
INSERT INTO enum_country VALUES( 'TG' , 'TOGO' );
INSERT INTO enum_country VALUES( 'TK' , 'TOKELAU' );
INSERT INTO enum_country VALUES( 'TO' , 'TONGA' );
INSERT INTO enum_country VALUES( 'TT' , 'TRINIDAD AND TOBAGO' );
INSERT INTO enum_country VALUES( 'TN' , 'TUNISIA' );
INSERT INTO enum_country VALUES( 'TR' , 'TURKEY' );
INSERT INTO enum_country VALUES( 'TM' , 'TURKMENISTAN' );
INSERT INTO enum_country VALUES( 'TC' , 'TURKS AND CAICOS ISLANDS' );
INSERT INTO enum_country VALUES( 'TV' , 'TUVALU' );
INSERT INTO enum_country VALUES( 'UG' , 'UGANDA' );
INSERT INTO enum_country VALUES( 'UA' , 'UKRAINE' );
INSERT INTO enum_country VALUES( 'AE' , 'UNITED ARAB EMIRATES' );
INSERT INTO enum_country VALUES( 'GB' , 'UNITED KINGDOM' );
INSERT INTO enum_country VALUES( 'US' , 'UNITED STATES' );
INSERT INTO enum_country VALUES( 'UM' , 'UNITED STATES MINOR OUTLYING ISLANDS' );
INSERT INTO enum_country VALUES( 'UY' , 'URUGUAY' );
INSERT INTO enum_country VALUES( 'UZ' , 'UZBEKISTAN' );
INSERT INTO enum_country VALUES( 'VU' , 'VANUATU' );
INSERT INTO enum_country VALUES( 'VE' , 'VENEZUELA' );
INSERT INTO enum_country VALUES( 'VN' , 'VIET NAM' );
INSERT INTO enum_country VALUES( 'VG' , 'VIRGIN ISLANDS, BRITISH' );
INSERT INTO enum_country VALUES( 'VI' , 'VIRGIN ISLANDS, U.S.' );
INSERT INTO enum_country VALUES( 'WF' , 'WALLIS AND FUTUNA' );
INSERT INTO enum_country VALUES( 'EH' , 'WESTERN SAHARA' );
INSERT INTO enum_country VALUES( 'YE' , 'YEMEN' );
INSERT INTO enum_country VALUES( 'ZM' , 'ZAMBIA' );
INSERT INTO enum_country VALUES( 'ZW' , 'ZIMBABWE' );
