-- kodovani
\encoding       LATIN2
-- nazvy zemi v cestine
UPDATE enum_country SET country_cs= 'Afghánistán'  WHERE ID= 'AF' ;
UPDATE enum_country SET country_cs= 'Albánie'  WHERE ID= 'AL' ;
UPDATE enum_country SET country_cs= 'Al¾írsko'  WHERE ID= 'DZ' ;
UPDATE enum_country SET country_cs= 'Americká Samoa'  WHERE ID= 'AS' ;
UPDATE enum_country SET country_cs= 'Americké Panenské ostrovy'  WHERE ID= 'VI' ;
UPDATE enum_country SET country_cs= 'Andorra'  WHERE ID= 'AD' ;
UPDATE enum_country SET country_cs= 'Angola'  WHERE ID= 'AO' ;
UPDATE enum_country SET country_cs= 'Anguilla'  WHERE ID= 'AI' ;
UPDATE enum_country SET country_cs= 'Antarktika'  WHERE ID= 'AQ' ;
UPDATE enum_country SET country_cs= 'Antigua a Barbuda'  WHERE ID= 'AG' ;
UPDATE enum_country SET country_cs= 'Argentina'  WHERE ID= 'AR' ;
UPDATE enum_country SET country_cs= 'Arménie'  WHERE ID= 'AM' ;
UPDATE enum_country SET country_cs= 'Aruba'  WHERE ID= 'AW' ;
UPDATE enum_country SET country_cs= 'Austrálie'  WHERE ID= 'AU' ;
UPDATE enum_country SET country_cs= 'Ázerbajd¾án'  WHERE ID= 'AZ' ;
UPDATE enum_country SET country_cs= 'Bahamy'  WHERE ID= 'BS' ;
UPDATE enum_country SET country_cs= 'Bahrajn'  WHERE ID= 'BH' ;
UPDATE enum_country SET country_cs= 'Bangladé¹'  WHERE ID= 'BD' ;
UPDATE enum_country SET country_cs= 'Barbados'  WHERE ID= 'BB' ;
UPDATE enum_country SET country_cs= 'Barma'  WHERE ID= 'MM' ;
UPDATE enum_country SET country_cs= 'Belgie'  WHERE ID= 'BE' ;
UPDATE enum_country SET country_cs= 'Belize'  WHERE ID= 'BZ' ;
UPDATE enum_country SET country_cs= 'Bìlorusko'  WHERE ID= 'BY' ;
UPDATE enum_country SET country_cs= 'Benin'  WHERE ID= 'BJ' ;
UPDATE enum_country SET country_cs= 'Bermudy'  WHERE ID= 'BM' ;
UPDATE enum_country SET country_cs= 'Bhútán'  WHERE ID= 'BT' ;
UPDATE enum_country SET country_cs= 'Bolívie'  WHERE ID= 'BO' ;
UPDATE enum_country SET country_cs= 'Bosna a Hercegovina'  WHERE ID= 'BA' ;
UPDATE enum_country SET country_cs= 'Botswana'  WHERE ID= 'BW' ;
UPDATE enum_country SET country_cs= 'Brazílie'  WHERE ID= 'BR' ;
UPDATE enum_country SET country_cs= 'Britské indickooceánské teritorium'  WHERE ID= 'IO' ;
UPDATE enum_country SET country_cs= 'Britské Panenské ostrovy'  WHERE ID= 'VG' ;
UPDATE enum_country SET country_cs= 'Brunej'  WHERE ID= 'BN' ;
UPDATE enum_country SET country_cs= 'Bulharsko'  WHERE ID= 'BG' ;
UPDATE enum_country SET country_cs= 'Burkina Faso'  WHERE ID= 'BF' ;
UPDATE enum_country SET country_cs= 'Burundi'  WHERE ID= 'BI' ;
UPDATE enum_country SET country_cs= 'Cookovy ostrovy'  WHERE ID= 'CK' ;
UPDATE enum_country SET country_cs= 'Èad'  WHERE ID= 'TD' ;
UPDATE enum_country SET country_cs= 'Èeská republika'  WHERE ID= 'CZ' ;
UPDATE enum_country SET country_cs= 'Èína'  WHERE ID= 'CN' ;
UPDATE enum_country SET country_cs= 'Dánsko'  WHERE ID= 'DK' ;
UPDATE enum_country SET country_cs= 'Dominika'  WHERE ID= 'DM' ;
UPDATE enum_country SET country_cs= 'Dominikánská republika'  WHERE ID= 'DO' ;
UPDATE enum_country SET country_cs= 'D¾ibuti'  WHERE ID= 'DJ' ;
UPDATE enum_country SET country_cs= 'Egypt'  WHERE ID= 'EG' ;
UPDATE enum_country SET country_cs= 'Ekvádor'  WHERE ID= 'EC' ;
UPDATE enum_country SET country_cs= 'Eritrea'  WHERE ID= 'ER' ;
UPDATE enum_country SET country_cs= 'Estonsko'  WHERE ID= 'EE' ;
UPDATE enum_country SET country_cs= 'Etiopie'  WHERE ID= 'ET' ;
UPDATE enum_country SET country_cs= 'Faerské ostrovy'  WHERE ID= 'FO' ;
UPDATE enum_country SET country_cs= 'Falklandy'  WHERE ID= 'FK' ;
UPDATE enum_country SET country_cs= 'Fid¾i'  WHERE ID= 'FJ' ;
UPDATE enum_country SET country_cs= 'Filipíny'  WHERE ID= 'PH' ;
UPDATE enum_country SET country_cs= 'Finsko'  WHERE ID= 'FI' ;
UPDATE enum_country SET country_cs= 'Francie'  WHERE ID= 'FR' ;
UPDATE enum_country SET country_cs= 'Francouzská Guyana'  WHERE ID= 'GF' ;
UPDATE enum_country SET country_cs= 'Francouzská Polynézie'  WHERE ID= 'PF' ;
UPDATE enum_country SET country_cs= 'Francouzská ji¾ní území'  WHERE ID= 'TF' ;
UPDATE enum_country SET country_cs= 'Gabun'  WHERE ID= 'GA' ;
UPDATE enum_country SET country_cs= 'Gambie'  WHERE ID= 'GM' ;
UPDATE enum_country SET country_cs= 'Ghana'  WHERE ID= 'GH' ;
UPDATE enum_country SET country_cs= 'Gibraltar'  WHERE ID= 'GI' ;
UPDATE enum_country SET country_cs= 'Grenada'  WHERE ID= 'GD' ;
UPDATE enum_country SET country_cs= 'Grónsko'  WHERE ID= 'GL' ;
UPDATE enum_country SET country_cs= 'Gruzie'  WHERE ID= 'GE' ;
UPDATE enum_country SET country_cs= 'Guadeloupe'  WHERE ID= 'GP' ;
UPDATE enum_country SET country_cs= 'Guam' WHERE ID= 'GU' ;
UPDATE enum_country SET country_cs= 'Guatemala'  WHERE ID= 'GT' ;
UPDATE enum_country SET country_cs= 'Guinea'  WHERE ID= 'GN' ;
UPDATE enum_country SET country_cs= 'Guinea-Bissau'  WHERE ID= 'GW' ;
UPDATE enum_country SET country_cs= 'Guyana'  WHERE ID= 'GY' ;
UPDATE enum_country SET country_cs= 'Haiti'  WHERE ID= 'HT' ;
UPDATE enum_country SET country_cs= 'Honduras'  WHERE ID= 'HN' ;
UPDATE enum_country SET country_cs= 'Hongkong'  WHERE ID= 'HK' ;
UPDATE enum_country SET country_cs= 'Chile'  WHERE ID= 'CL' ;
UPDATE enum_country SET country_cs= 'Chorvatsko'  WHERE ID= 'HR' ;
UPDATE enum_country SET country_cs= 'Indie'  WHERE ID= 'IN' ;
UPDATE enum_country SET country_cs= 'Indonézie'  WHERE ID= 'ID' ;
UPDATE enum_country SET country_cs= 'Irák'  WHERE ID= 'IQ' ;
UPDATE enum_country SET country_cs= 'Írán'  WHERE ID= 'IR' ;
UPDATE enum_country SET country_cs= 'Irsko'  WHERE ID= 'IE' ;
UPDATE enum_country SET country_cs= 'Island'  WHERE ID= 'IS' ;
UPDATE enum_country SET country_cs= 'Itálie'  WHERE ID= 'IT' ;
UPDATE enum_country SET country_cs= 'Izrael'  WHERE ID= 'IL' ;
UPDATE enum_country SET country_cs= 'Jamajka'  WHERE ID= 'JM' ;
UPDATE enum_country SET country_cs= 'Japonsko'  WHERE ID= 'JP' ;
UPDATE enum_country SET country_cs= 'Jemen'  WHERE ID= 'YE' ;
UPDATE enum_country SET country_cs= 'Jihoafrická republika'  WHERE ID= 'ZA' ;
UPDATE enum_country SET country_cs= 'Ji¾ní Georgie'  WHERE ID= 'GS' ;
UPDATE enum_country SET country_cs= 'Jordánsko'  WHERE ID= 'JO' ;
UPDATE enum_country SET country_cs= 'Kajmanské ostrovy'  WHERE ID= 'KY' ;
UPDATE enum_country SET country_cs= 'Kambod¾a'  WHERE ID= 'KH' ;
UPDATE enum_country SET country_cs= 'Kamerun'  WHERE ID= 'CM' ;
UPDATE enum_country SET country_cs= 'Kanada'  WHERE ID= 'CA' ;
UPDATE enum_country SET country_cs= 'Kapverdy'  WHERE ID= 'CV' ;
UPDATE enum_country SET country_cs= 'Katar'  WHERE ID= 'QA' ;
UPDATE enum_country SET country_cs= 'Kazachstán'  WHERE ID= 'KZ' ;
UPDATE enum_country SET country_cs= 'Keòa'  WHERE ID= 'KE' ;
UPDATE enum_country SET country_cs= 'Kiribati'  WHERE ID= 'KI' ;
UPDATE enum_country SET country_cs= 'Kolumbie'  WHERE ID= 'CO' ;
UPDATE enum_country SET country_cs= 'Kokosové ostrovy'  WHERE ID= 'CC' ;
UPDATE enum_country SET country_cs= 'Komory'  WHERE ID= 'KM' ;
UPDATE enum_country SET country_cs= 'Kongo'  WHERE ID= 'CG' ;
UPDATE enum_country SET country_cs= 'Kongo (Demokratická republika Kongo)'  WHERE ID= 'CD' ;
UPDATE enum_country SET country_cs= 'Severní Korea (Korejská lidovì demokratická republika)'  WHERE ID= 'KP' ;
UPDATE enum_country SET country_cs= 'Korea (Korejská republika)'  WHERE ID= 'KR' ;
UPDATE enum_country SET country_cs= 'Kostarika'  WHERE ID= 'CR' ;
UPDATE enum_country SET country_cs= 'Kuba'  WHERE ID= 'CU' ;
UPDATE enum_country SET country_cs= 'Kuvajt'  WHERE ID= 'KW' ;
UPDATE enum_country SET country_cs= 'Kypr'  WHERE ID= 'CY' ;
UPDATE enum_country SET country_cs= 'Kyrgyzstán'  WHERE ID= 'KG' ;
UPDATE enum_country SET country_cs= 'Laos'  WHERE ID= 'LA' ;
UPDATE enum_country SET country_cs= 'Libanon'  WHERE ID= 'LB' ;
UPDATE enum_country SET country_cs= 'Lesotho'  WHERE ID= 'LS' ;
UPDATE enum_country SET country_cs= 'Libérie'  WHERE ID= 'LR' ;
UPDATE enum_country SET country_cs= 'Libye'  WHERE ID= 'LY' ;
UPDATE enum_country SET country_cs= 'Lichten¹tejnsko'  WHERE ID= 'LI' ;
UPDATE enum_country SET country_cs= 'Litva'  WHERE ID= 'LT' ;
UPDATE enum_country SET country_cs= 'Loty¹sko'  WHERE ID= 'LV' ;
UPDATE enum_country SET country_cs= 'Lucembursko'  WHERE ID= 'LU' ;
UPDATE enum_country SET country_cs= 'Makao'  WHERE ID= 'MO' ;
UPDATE enum_country SET country_cs= 'Makedonie'  WHERE ID= 'MK' ;
UPDATE enum_country SET country_cs= 'Madagaskar'  WHERE ID= 'MG' ;
UPDATE enum_country SET country_cs= 'Maïarsko'  WHERE ID= 'HU' ;
UPDATE enum_country SET country_cs= 'Malawi'  WHERE ID= 'MW' ;
UPDATE enum_country SET country_cs= 'Malajsie'  WHERE ID= 'MY' ;
UPDATE enum_country SET country_cs= 'Maledivy'  WHERE ID= 'MV' ;
UPDATE enum_country SET country_cs= 'Mali'  WHERE ID= 'ML' ;
UPDATE enum_country SET country_cs= 'Malta'  WHERE ID= 'MT' ;
UPDATE enum_country SET country_cs= 'Maroko'  WHERE ID= 'MA' ;
UPDATE enum_country SET country_cs= 'Marshallovy ostrovy'  WHERE ID= 'MH' ;
UPDATE enum_country SET country_cs= 'Martinik'  WHERE ID= 'MQ' ;
UPDATE enum_country SET country_cs= 'Mauretánie'  WHERE ID= 'MR' ;
UPDATE enum_country SET country_cs= 'Mauricius'  WHERE ID= 'MU' ;
UPDATE enum_country SET country_cs= 'Mayotte'  WHERE ID= 'YT' ;
UPDATE enum_country SET country_cs= 'Mexiko'  WHERE ID= 'MX' ;
UPDATE enum_country SET country_cs= 'Mikronésie'  WHERE ID= 'FM' ;
UPDATE enum_country SET country_cs= 'Moldavsko'  WHERE ID= 'MD' ;
UPDATE enum_country SET country_cs= 'Monako'  WHERE ID= 'MC' ;
UPDATE enum_country SET country_cs= 'Mongolsko'  WHERE ID= 'MN' ;
UPDATE enum_country SET country_cs= 'Montserrat'  WHERE ID= 'MS' ;
UPDATE enum_country SET country_cs= 'Mosambik'  WHERE ID= 'MZ' ;
UPDATE enum_country SET country_cs= 'Namíbie'  WHERE ID= 'NA' ;
UPDATE enum_country SET country_cs= 'Nauru'  WHERE ID= 'NR' ;
UPDATE enum_country SET country_cs= 'Nìmecko'  WHERE ID= 'DE' ;
UPDATE enum_country SET country_cs= 'Nepál'  WHERE ID= 'NP' ;
UPDATE enum_country SET country_cs= 'Niger'  WHERE ID= 'NE' ;
UPDATE enum_country SET country_cs= 'Nigérie'  WHERE ID= 'NG' ;
UPDATE enum_country SET country_cs= 'Nikaragua'  WHERE ID= 'NI' ;
UPDATE enum_country SET country_cs= 'Nizozemí'  WHERE ID= 'NL' ;
UPDATE enum_country SET country_cs= 'Nizozemské Antily'  WHERE ID= 'AN' ;
UPDATE enum_country SET country_cs= 'Niue'  WHERE ID= 'NU' ;
UPDATE enum_country SET country_cs= 'Norfolk'  WHERE ID= 'NF' ;
UPDATE enum_country SET country_cs= 'Norsko'  WHERE ID= 'NO' ;
UPDATE enum_country SET country_cs= 'Nová Kaledonie'  WHERE ID= 'NC' ;
UPDATE enum_country SET country_cs= 'Nový Zéland'  WHERE ID= 'NZ' ;
UPDATE enum_country SET country_cs= 'Omán'  WHERE ID= 'OM' ;
UPDATE enum_country SET country_cs= 'Pákistán'  WHERE ID= 'PK' ;
UPDATE enum_country SET country_cs= 'Palau'  WHERE ID= 'PW' ;
UPDATE enum_country SET country_cs= 'Palestina'  WHERE ID= 'PS' ;
UPDATE enum_country SET country_cs= 'Panama'  WHERE ID= 'PA' ;
UPDATE enum_country SET country_cs= 'Papua Nová Guinea'  WHERE ID= 'PG' ;
UPDATE enum_country SET country_cs= 'Paraguay'  WHERE ID= 'PY' ;
UPDATE enum_country SET country_cs= 'Peru'  WHERE ID= 'PE' ;
UPDATE enum_country SET country_cs= 'Pitcairnovy ostrovy'  WHERE ID= 'PN' ;
UPDATE enum_country SET country_cs= 'Pobøe¾í slonoviny'  WHERE ID= 'CI' ;
UPDATE enum_country SET country_cs= 'Polsko'  WHERE ID= 'PL' ;
UPDATE enum_country SET country_cs= 'Portoriko'  WHERE ID= 'PR' ;
UPDATE enum_country SET country_cs= 'Portugalsko'  WHERE ID= 'PT' ;
UPDATE enum_country SET country_cs= 'Rakousko'  WHERE ID= 'AT' ;
UPDATE enum_country SET country_cs= 'Réunion'  WHERE ID= 'RE' ;
UPDATE enum_country SET country_cs= 'Rovníková Guinea'  WHERE ID= 'GQ' ;
UPDATE enum_country SET country_cs= 'Rumunsko'  WHERE ID= 'RO' ;
UPDATE enum_country SET country_cs= 'Rusko'  WHERE ID= 'RU' ;
UPDATE enum_country SET country_cs= 'Rwanda'  WHERE ID= 'RW' ;
UPDATE enum_country SET country_cs= 'Øecko'  WHERE ID= 'GR' ;
UPDATE enum_country SET country_cs= 'Salvador'  WHERE ID= 'SV' ;
UPDATE enum_country SET country_cs= 'Samoa'  WHERE ID= 'WS' ;
UPDATE enum_country SET country_cs= 'San Marino'  WHERE ID= 'SM' ;
UPDATE enum_country SET country_cs= 'Saúdská Arábie'  WHERE ID= 'SA' ;
UPDATE enum_country SET country_cs= 'Senegal'  WHERE ID= 'SN' ;
UPDATE enum_country SET country_cs= 'Severní Mariany'  WHERE ID= 'MP' ;
UPDATE enum_country SET country_cs= 'Seychely'  WHERE ID= 'SC' ;
UPDATE enum_country SET country_cs= 'Sierra Leone'  WHERE ID= 'SL' ;
UPDATE enum_country SET country_cs= 'Singapur'  WHERE ID= 'SG' ;
UPDATE enum_country SET country_cs= 'Slovensko'  WHERE ID= 'SK' ;
UPDATE enum_country SET country_cs= 'Slovinsko'  WHERE ID= 'SI' ;
UPDATE enum_country SET country_cs= 'Somálsko'  WHERE ID= 'SO' ;
UPDATE enum_country SET country_cs= 'Spojené arabské emiráty'  WHERE ID= 'AE' ;
UPDATE enum_country SET country_cs= 'Spojené státy americké'  WHERE ID= 'US' ;
UPDATE enum_country SET country_cs= 'Srbsko a Èerná hora'  WHERE ID= 'CS' ;
UPDATE enum_country SET country_cs= 'Srí Lanka (Cejlon)'  WHERE ID= 'LK' ;
UPDATE enum_country SET country_cs= 'Støedoafrická republika'  WHERE ID= 'CF' ;
UPDATE enum_country SET country_cs= 'Súdán'  WHERE ID= 'SD' ;
UPDATE enum_country SET country_cs= 'Surinam'  WHERE ID= 'SR' ;
UPDATE enum_country SET country_cs= 'Svatá Helena'  WHERE ID= 'SH' ;
UPDATE enum_country SET country_cs= 'Svatá Lucie'  WHERE ID= 'LC' ;
UPDATE enum_country SET country_cs= 'Svazijsko'  WHERE ID= 'SZ' ;
UPDATE enum_country SET country_cs= 'Sýrie'  WHERE ID= 'SY' ;
UPDATE enum_country SET country_cs= '©alomounovy ostrovy'  WHERE ID= 'SB' ;
UPDATE enum_country SET country_cs= '©panìlsko'  WHERE ID= 'ES' ;
UPDATE enum_country SET country_cs= '©picberky'  WHERE ID= 'SJ' ;
UPDATE enum_country SET country_cs= '©védsko'  WHERE ID= 'SE' ;
UPDATE enum_country SET country_cs= '©výcarsko'  WHERE ID= 'CH' ;
UPDATE enum_country SET country_cs= 'Tád¾ikistán'  WHERE ID= 'TJ' ;
UPDATE enum_country SET country_cs= 'Tanzánie'  WHERE ID= 'TZ' ;
UPDATE enum_country SET country_cs= 'Thajsko'  WHERE ID= 'TH' ;
UPDATE enum_country SET country_cs= 'Tchajwan'  WHERE ID= 'TW' ;
UPDATE enum_country SET country_cs= 'Togo'  WHERE ID= 'TG' ;
UPDATE enum_country SET country_cs= 'Tokelau'  WHERE ID= 'TK' ;
UPDATE enum_country SET country_cs= 'Tonga'  WHERE ID= 'TO' ;
UPDATE enum_country SET country_cs= 'Trinidad a Tobago'  WHERE ID= 'TT' ;
UPDATE enum_country SET country_cs= 'Tunisko'  WHERE ID= 'TN' ;
UPDATE enum_country SET country_cs= 'Turecko'  WHERE ID= 'TR' ;
UPDATE enum_country SET country_cs= 'Turkmenistán'  WHERE ID= 'TM' ;
UPDATE enum_country SET country_cs= 'Tuvalu'  WHERE ID= 'TV' ;
UPDATE enum_country SET country_cs= 'Uganda'  WHERE ID= 'UG' ;
UPDATE enum_country SET country_cs= 'Ukrajina'  WHERE ID= 'UA' ;
UPDATE enum_country SET country_cs= 'Uruguay'  WHERE ID= 'UY' ;
UPDATE enum_country SET country_cs= 'Uzbekistán'  WHERE ID= 'UZ' ;
UPDATE enum_country SET country_cs= 'Vánoèní ostrov'  WHERE ID= 'CX' ;
UPDATE enum_country SET country_cs= 'Vanuatu'  WHERE ID= 'VU' ;
UPDATE enum_country SET country_cs= 'Vatikán'  WHERE ID= 'VA' ;
UPDATE enum_country SET country_cs= 'Velká Británie a Severní Irsko'  WHERE ID= 'GB' ;
UPDATE enum_country SET country_cs= 'Venezuela'  WHERE ID= 'VE' ;
UPDATE enum_country SET country_cs= 'Vietnam'  WHERE ID= 'VN' ;
UPDATE enum_country SET country_cs= 'Východní timor'  WHERE ID= 'TL' ;
UPDATE enum_country SET country_cs= 'Wallisovy ostrovy'  WHERE ID= 'WF' ;
UPDATE enum_country SET country_cs= 'Zambie'  WHERE ID= 'ZM' ;
UPDATE enum_country SET country_cs= 'Západní Sahara'  WHERE ID= 'EH' ;
UPDATE enum_country SET country_cs= 'Zimbabwe'  WHERE ID= 'ZW' ;
