---
--- don't forget to update database schema version
---
UPDATE enum_parameters SET val = '2.32.0' WHERE id = 1;


ALTER TABLE registraracl ALTER COLUMN password SET DATA TYPE VARCHAR(1024);

COMMENT ON COLUMN registraracl.cert IS 'fingerprint of registrar''s certificate';
COMMENT ON COLUMN registraracl.password IS 'data generated by password hashing function';

UPDATE registraracl SET password = '$plaintext$' || password;
